//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreWithImage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BookStoreEntities : DbContext
    {
        public BookStoreEntities()
            : base("name=BookStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
    
        public virtual ObjectResult<GetBooksOfPage_Result> GetBooksOfPage(Nullable<int> bookPerPage, Nullable<int> pageNumer)
        {
            var bookPerPageParameter = bookPerPage.HasValue ?
                new ObjectParameter("BookPerPage", bookPerPage) :
                new ObjectParameter("BookPerPage", typeof(int));
    
            var pageNumerParameter = pageNumer.HasValue ?
                new ObjectParameter("PageNumer", pageNumer) :
                new ObjectParameter("PageNumer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBooksOfPage_Result>("GetBooksOfPage", bookPerPageParameter, pageNumerParameter);
        }
    }
}
